# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.public_key_defines_the_keys_available_for_use_with_tendermint_validators import PublicKeyDefinesTheKeysAvailableForUseWithTendermintValidators  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicKeyDefinesTheKeysAvailableForUseWithTendermintValidators(unittest.TestCase):
    """PublicKeyDefinesTheKeysAvailableForUseWithTendermintValidators unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicKeyDefinesTheKeysAvailableForUseWithTendermintValidators(self):
        """Test PublicKeyDefinesTheKeysAvailableForUseWithTendermintValidators"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.public_key_defines_the_keys_available_for_use_with_tendermint_validators.PublicKeyDefinesTheKeysAvailableForUseWithTendermintValidators()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
