# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20023_default_node_info import InlineResponse20023DefaultNodeInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20023DefaultNodeInfo(unittest.TestCase):
    """InlineResponse20023DefaultNodeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023DefaultNodeInfo(self):
        """Test InlineResponse20023DefaultNodeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20023_default_node_info.InlineResponse20023DefaultNodeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
