# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_group_v1_query_proposals_by_group_policy_response import CosmosGroupV1QueryProposalsByGroupPolicyResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosGroupV1QueryProposalsByGroupPolicyResponse(unittest.TestCase):
    """CosmosGroupV1QueryProposalsByGroupPolicyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosGroupV1QueryProposalsByGroupPolicyResponse(self):
        """Test CosmosGroupV1QueryProposalsByGroupPolicyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_group_v1_query_proposals_by_group_policy_response.CosmosGroupV1QueryProposalsByGroupPolicyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
