# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CosmosGroupV1GroupPolicyInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'group_id': 'str',
        'admin': 'str',
        'metadata': 'str',
        'version': 'str',
        'decision_policy': 'dict(str, object)',
        'created_at': 'datetime'
    }

    attribute_map = {
        'address': 'address',
        'group_id': 'group_id',
        'admin': 'admin',
        'metadata': 'metadata',
        'version': 'version',
        'decision_policy': 'decision_policy',
        'created_at': 'created_at'
    }

    def __init__(self, address=None, group_id=None, admin=None, metadata=None, version=None, decision_policy=None, created_at=None):  # noqa: E501
        """CosmosGroupV1GroupPolicyInfo - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._group_id = None
        self._admin = None
        self._metadata = None
        self._version = None
        self._decision_policy = None
        self._created_at = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if group_id is not None:
            self.group_id = group_id
        if admin is not None:
            self.admin = admin
        if metadata is not None:
            self.metadata = metadata
        if version is not None:
            self.version = version
        if decision_policy is not None:
            self.decision_policy = decision_policy
        if created_at is not None:
            self.created_at = created_at

    @property
    def address(self):
        """Gets the address of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501

        address is the account address of group policy.  # noqa: E501

        :return: The address of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CosmosGroupV1GroupPolicyInfo.

        address is the account address of group policy.  # noqa: E501

        :param address: The address of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def group_id(self):
        """Gets the group_id of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501

        group_id is the unique ID of the group.  # noqa: E501

        :return: The group_id of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this CosmosGroupV1GroupPolicyInfo.

        group_id is the unique ID of the group.  # noqa: E501

        :param group_id: The group_id of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def admin(self):
        """Gets the admin of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501

        admin is the account address of the group admin.  # noqa: E501

        :return: The admin of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :rtype: str
        """
        return self._admin

    @admin.setter
    def admin(self, admin):
        """Sets the admin of this CosmosGroupV1GroupPolicyInfo.

        admin is the account address of the group admin.  # noqa: E501

        :param admin: The admin of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :type: str
        """

        self._admin = admin

    @property
    def metadata(self):
        """Gets the metadata of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501

        metadata is any arbitrary metadata to attached to the group policy.  # noqa: E501

        :return: The metadata of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :rtype: str
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this CosmosGroupV1GroupPolicyInfo.

        metadata is any arbitrary metadata to attached to the group policy.  # noqa: E501

        :param metadata: The metadata of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :type: str
        """

        self._metadata = metadata

    @property
    def version(self):
        """Gets the version of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501

        version is used to track changes to a group's GroupPolicyInfo structure that would create a different result on a running proposal.  # noqa: E501

        :return: The version of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this CosmosGroupV1GroupPolicyInfo.

        version is used to track changes to a group's GroupPolicyInfo structure that would create a different result on a running proposal.  # noqa: E501

        :param version: The version of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def decision_policy(self):
        """Gets the decision_policy of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501

        decision_policy specifies the group policy's decision policy.  # noqa: E501

        :return: The decision_policy of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._decision_policy

    @decision_policy.setter
    def decision_policy(self, decision_policy):
        """Sets the decision_policy of this CosmosGroupV1GroupPolicyInfo.

        decision_policy specifies the group policy's decision policy.  # noqa: E501

        :param decision_policy: The decision_policy of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :type: dict(str, object)
        """

        self._decision_policy = decision_policy

    @property
    def created_at(self):
        """Gets the created_at of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501

        created_at is a timestamp specifying when a group policy was created.  # noqa: E501

        :return: The created_at of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this CosmosGroupV1GroupPolicyInfo.

        created_at is a timestamp specifying when a group policy was created.  # noqa: E501

        :param created_at: The created_at of this CosmosGroupV1GroupPolicyInfo.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CosmosGroupV1GroupPolicyInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CosmosGroupV1GroupPolicyInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
